### ISSUE TITLE
input/output error on kernel 5.12

### ISSUE THREAD

**Issue by alirezawaskari** [Lenovsky/ipman#3]
hey
just updated my manjaro kernel from 5.11 to 512 and noticed my ipman service has failed; checked and took input/output error on line 79 of the binary file on /usr/bin/ipman,
peace.

**Comment by yoomaxxx** [comment]
I have this error too

**Comment by petsam** [comment]
Confirmed for `linux` kernel.
It still works on `linux-lts`.

---
There is a bug report that almost matches.
https://bugzilla.kernel.org/show_bug.cgi?id=212985#c1

**Comment by lenowski** [comment]
Fixed on `linux 5.12.7`
